import os
from io import BytesIO
from django.http import HttpResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from django.conf import settings

def generate_system_report_pdf(tenders, total_tenders, total_bids, total_disbursed, report_subtitle, admin_user):
    """
    Generates a structured, landscape A to Z System Report with improved spacing and layout stability.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=landscape(A4), 
                            rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    elements = []
    styles = getSampleStyleSheet()
    
    # Custom Styles
    styles.add(ParagraphStyle(name='MainHeader', fontName='Helvetica-Bold', fontSize=30, textColor=colors.HexColor('#0f2a5e'), alignment=1, spaceAfter=12))
    styles.add(ParagraphStyle(name='SubHeader', fontName='Helvetica-Bold', fontSize=15, textColor=colors.HexColor('#1e56db'), alignment=1, spaceAfter=40))
    styles.add(ParagraphStyle(name='SectionHead', fontName='Helvetica-Bold', fontSize=18, textColor=colors.HexColor('#0f2a5e'), spaceBefore=30, spaceAfter=15))
    styles.add(ParagraphStyle(name='TenderTitle', fontName='Helvetica-Bold', fontSize=13, textColor=colors.white))
    styles.add(ParagraphStyle(name='CellText', fontName='Helvetica', fontSize=8.5, leading=11))
    styles.add(ParagraphStyle(name='CellBold', fontName='Helvetica-Bold', fontSize=8.5, leading=11))
    styles.add(ParagraphStyle(name='MetaLabel', fontName='Helvetica-Bold', fontSize=9, textColor=colors.HexColor('#475569')))
    styles.add(ParagraphStyle(name='MetaValue', fontName='Helvetica', fontSize=9, textColor=colors.HexColor('#1e293b')))
    
    # ── 1. FRONT PAGE ──
    logo_path = os.path.join(settings.BASE_DIR, 'public', 'static', 'images', 'Logo', 'logo-icon.png')
    if os.path.exists(logo_path):
        logo = Image(logo_path, 1.6 * inch, 1.6 * inch)
        logo.hAlign = 'CENTER'
        elements.append(Spacer(1, 0.8 * inch))
        elements.append(logo)
        elements.append(Spacer(1, 0.4 * inch))

    elements.append(Paragraph("eBHARAT TENDER PORTAL", styles['MainHeader']))
    elements.append(Paragraph("Official System Audit & Full Lifecycle Report", styles['SubHeader']))
    
    # Front Page Info Box
    fp_info = [
        [Paragraph("<b>Report Scope:</b>", styles['CellBold']), "Complete System A to Z Data Archive"],
        [Paragraph("<b>Generated By:</b>", styles['CellBold']), f"{admin_user.get_full_name() or admin_user.username}"],
        [Paragraph("<b>Reporting Period:</b>", styles['CellBold']), report_subtitle],
        [Paragraph("<b>Authority:</b>", styles['CellBold']), "Government of India / Administrative Division"]
    ]
    fp_table = Table(fp_info, colWidths=[2.2*inch, 4.5*inch])
    fp_table.setStyle(TableStyle([
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('BOTTOMPADDING', (0,0), (-1,-1), 12),
        ('TOPPADDING', (0,0), (-1,-1), 12),
    ]))
    elements.append(Spacer(1, 0.5 * inch))
    elements.append(fp_table)
    elements.append(Spacer(1, 1.2 * inch))
    elements.append(Paragraph("STRICTLY CONFIDENTIAL - UNAUTHORIZED SHARING PROHIBITED", ParagraphStyle(name='Warning', fontSize=9, textColor=colors.red, alignment=1, fontName='Helvetica-Bold')))
    
    elements.append(PageBreak())
    
    # ── 2. SYSTEM SUMMARY (Killed Overlap) ──
    elements.append(Paragraph("Current System Summary", styles['SectionHead']))
    summary_data = [
        [Paragraph("<b>Total Active Tenders</b>", styles['CellBold']), Paragraph("<b>Total Bids Received</b>", styles['CellBold']), Paragraph("<b>Awarded Funds (INR)</b>", styles['CellBold'])],
        [Paragraph(f"<font size=20><b>{total_tenders}</b></font>", styles['CellText']), 
         Paragraph(f"<font size=20><b>{total_bids}</b></font>", styles['CellText']), 
         Paragraph(f"<font size=20><b>{float(total_disbursed):,.2f}</b></font>", styles['CellText'])]
    ]
    # Center the summary table
    summary_table = Table(summary_data, colWidths=[3*inch, 3*inch, 3.5*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f8fafc')),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#cbd5e1')),
        ('BOTTOMPADDING', (0,0), (-1,-1), 20),
        ('TOPPADDING', (0,0), (-1,-1), 20),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 40))

    # ── 3. TENDER BY TENDER DETAILS (A to Z) ──
    for idx, tender in enumerate(tenders, 1):
        tender_elements = []  # Group everything for this tender
        
        # 3a. HEADER (Nicer spacing)
        header_data = [[Paragraph(f"{idx}. {tender.title} (ID: {tender.tender_id})", styles['TenderTitle'])]]
        header_table = Table(header_data, colWidths=[doc.width])
        header_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#0f2a5e')),
            ('TOPPADDING', (0,0), (-1,-1), 12),
            ('BOTTOMPADDING', (0,0), (-1,-1), 12),
            ('LEFTPADDING', (0,0), (-1,-1), 15),
        ]))
        tender_elements.append(header_table)
        
        # 3b. METADATA (Boxed for separation)
        meta_grid = [
            [Paragraph("Department:", styles['MetaLabel']), Paragraph(tender.department, styles['MetaValue']), 
             Paragraph("Location:", styles['MetaLabel']), Paragraph(tender.location, styles['MetaValue'])],
            [Paragraph("Category:", styles['MetaLabel']), Paragraph(tender.category, styles['MetaValue']), 
             Paragraph("Status:", styles['MetaLabel']), Paragraph(tender.get_status_display(), styles['MetaValue'])],
            [Paragraph("Est. Value:", styles['MetaLabel']), Paragraph(f"INR {tender.estimated_value:,.2f}", styles['MetaValue']), 
             Paragraph("EMD Amount:", styles['MetaLabel']), Paragraph(f"INR {tender.emd_amount:,.2f}", styles['MetaValue'])],
            [Paragraph("Published:", styles['MetaLabel']), Paragraph(tender.publish_date.strftime('%d/%m/%Y'), styles['MetaValue']), 
             Paragraph("Closing:", styles['MetaLabel']), Paragraph(tender.closing_date.strftime('%d/%m/%Y'), styles['MetaValue'])],
        ]
        mg_table = Table(meta_grid, colWidths=[1.4*inch, 3.3*inch, 1.4*inch, 3.3*inch])
        mg_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('LEFTPADDING', (0,0), (-1,-1), 15),
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#ffffff')),
            ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor('#f1f5f9')),
        ]))
        tender_elements.append(mg_table)
        tender_elements.append(Spacer(1, 15))
        
        # 3c. BIDDERS TABLE (Wide spacing)
        bids = tender.applications.all().order_by('-status')
        if bids.exists():
            bid_headers = [
                Paragraph("<b>Company / GST</b>", styles['CellBold']),
                Paragraph("<b>Contact Details</b>", styles['CellBold']),
                Paragraph("<b>Registered Office</b>", styles['CellBold']),
                Paragraph("<b>Bid Amount</b>", styles['CellBold']),
                Paragraph("<b>Outcome</b>", styles['CellBold'])
            ]
            bid_rows = [bid_headers]
            
            for bid in bids:
                is_award = (bid.status == 'awarded')
                bid_rows.append([
                    Paragraph(f"<b>{bid.company_name}</b><br/><font color='#64748b' size=7.5>GST: {bid.gst_number}</font>", styles['CellText']),
                    Paragraph(f"<b>{bid.bidder_name}</b><br/><font size=7.5>{bid.mobile_number}<br/>{bid.official_email}</font>", styles['CellText']),
                    Paragraph(f"{bid.city}, {bid.state}<br/><font size=7.5>PIN: {bid.pin_code}</font>", styles['CellText']),
                    Paragraph(f"<b>INR {bid.bid_amount:,.2f}</b>", styles['CellText']),
                    Paragraph(f"<b>{bid.get_status_display()}</b>", styles['CellText'])
                ])
            
            bt_table = Table(bid_rows, colWidths=[2.2*inch, 2.5*inch, 2.3*inch, 1.3*inch, 1.1*inch], repeatRows=1)
            
            # Base Table Styling
            bt_styles = [
                ('BACKGROUND', (0,0), (-1, 0), colors.HexColor('#f1f5f9')),
                ('GRID', (0,0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
                ('VALIGN', (0,0), (-1, -1), 'TOP'),
                ('LEFTPADDING', (0,0), (-1,-1), 10),
                ('RIGHTPADDING', (0,0), (-1,-1), 10),
                ('BOTTOMPADDING', (0,0), (-1, -1), 10),
                ('TOPPADDING', (0,0), (-1, -1), 10),
            ]
            
            # Application Awards Highlighting
            for r_idx, bid in enumerate(bids, 1):
                if bid.status == 'awarded':
                    bt_styles.append(('BACKGROUND', (0, r_idx), (-1, r_idx), colors.HexColor('#dcfce7')))
                    bt_styles.append(('LINEBELOW', (0, r_idx), (-1, r_idx), 1, colors.HexColor('#16a34a')))
                    bt_styles.append(('LINEABOVE', (0, r_idx), (-1, r_idx), 1, colors.HexColor('#16a34a')))
            
            bt_table.setStyle(TableStyle(bt_styles))
            tender_elements.append(bt_table)
        else:
            tender_elements.append(Paragraph("<i>No bid applications received for this recruitment.</i>", styles['CellText']))

        # Append grouped tender sections with a large gap
        elements.append(KeepTogether(tender_elements))
        elements.append(Spacer(1, 40))

    # Master Footer
    def header_footer(canvas, doc):
        canvas.saveState()
        width, height = landscape(A4)
        canvas.setFont('Helvetica-Bold', 8.5)
        canvas.setFillColor(colors.HexColor('#64748b'))
        canvas.drawString(40, 25, "eBharat Tender Portal | Official Accountability & Audit Statement")
        canvas.drawRightString(width-40, 25, f"Electronic Copy | Page {canvas.getPageNumber()}")
        canvas.setStrokeColor(colors.HexColor('#cbd5e1'))
        canvas.line(40, 38, width-40, 38)
        canvas.restoreState()

    doc.build(elements, onFirstPage=header_footer, onLaterPages=header_footer)
    
    pdf_content = buffer.getvalue()
    buffer.close()
    
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="eBharat_System_Lifecycle_Audit.pdf"'
    response.write(pdf_content)
    return response
