from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from django.conf import settings
import io
import os

def draw_header(canvas, doc):
    canvas.saveState()
    
    # Header styling
    canvas.setFont('Helvetica-Bold', 22)
    canvas.setFillColor(colors.HexColor('#0d2b6b'))
    
    # We don't have an exact logo image, so we draw the Ashoka chakra like symbol or just text
    # Let's draw a professional header
    
    # eBharat Tender Portal Title
    canvas.drawCentredString(A4[0] / 2.0, A4[1] - 50, "eBharat Tender Portal")
    
    canvas.setFont('Helvetica', 12)
    canvas.setFillColor(colors.HexColor('#444444'))
    canvas.drawCentredString(A4[0] / 2.0, A4[1] - 68, "e-Procurement System, Government of India")
    canvas.drawCentredString(A4[0] / 2.0, A4[1] - 82, "Official Communication Document")
    
    # Double line break
    canvas.setStrokeColor(colors.HexColor('#0d2b6b'))
    canvas.setLineWidth(2)
    canvas.line(doc.leftMargin, A4[1] - 100, A4[0] - doc.rightMargin, A4[1] - 100)
    canvas.setLineWidth(0.5)
    canvas.setStrokeColor(colors.HexColor('#138808'))
    canvas.line(doc.leftMargin, A4[1] - 103, A4[0] - doc.rightMargin, A4[1] - 103)

    # Footer
    canvas.setFont('Helvetica', 9)
    canvas.setFillColor(colors.grey)
    canvas.drawString(doc.leftMargin, 30, "Generated by eBharat Tender System")
    canvas.drawRightString(A4[0] - doc.rightMargin, 30, f"Page {doc.page}")

    canvas.restoreState()


def generate_official_pdf(subject, acknowledgement_text, details_dict):
    """
    Generates a professional Government A4 PDF.
    
    :param subject: String, central subject of the document.
    :param details_dict: Dictionary of details for the table { "Title": "Value", ... }
    :param acknowledgement_text: String or list of Strings for the acknowledgement paragraph.
    :return: PDF bytes
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=130, # Leave space for the draw_header
        bottomMargin=60
    )

    elements = []
    styles = getSampleStyleSheet()

    # 1. Styles
    subject_style = ParagraphStyle(
        'Subject',
        parent=styles['Heading2'],
        alignment=1, # Center
        fontSize=15,
        textColor=colors.black,
        spaceAfter=30,
        fontName='Helvetica-Bold'
    )
    
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.HexColor('#333333'),
        spaceAfter=12,
        leading=16,
        fontName='Helvetica'
    )

    bold_label_style = ParagraphStyle(
        'BoldLabel',
        parent=normal_style,
        fontName='Helvetica-Bold'
    )

    # 2. Subject Middle
    elements.append(Paragraph(f"<b><u>SUBJECT: {subject}</u></b>", subject_style))

    # 4. Acknowledgement
    elements.append(Spacer(1, 0.1 * inch))
    
    if isinstance(acknowledgement_text, list):
        for para in acknowledgement_text:
            elements.append(Paragraph(para, normal_style))
    else:
        elements.append(Paragraph(acknowledgement_text, normal_style))
        
    elements.append(Spacer(1, 0.6 * inch))

     # 3. Details Table
    if details_dict:
        elements.append(Paragraph("<b> Detailed Particulars</b>", styles['Heading3']))
        elements.append(Spacer(1, 0.1 * inch))
        
        table_data = []
        for key, value in details_dict.items():
            table_data.append([
                Paragraph(f"<b>{key}</b>", styles['Normal']), 
                Paragraph(str(value), styles['Normal'])
            ])
            
        details_table = Table(table_data, colWidths=[200, 280])
        details_table.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cdcdcd')),
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f7f7f7')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#333333')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('PADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(details_table)
        elements.append(Spacer(1, 0.3 * inch))

    # 6. Page Break for Terms & Conditions
    elements.append(PageBreak())
    
    # 7. Terms and Conditions
    elements.append(Paragraph("<b><u>TERMS AND CONDITIONS</u></b>", subject_style))
    
    tc_intro = "The following terms and conditions govern the validity of the aforementioned document and any subsequent automated or manual processes in the eBharat Tender Portal."
    elements.append(Paragraph(tc_intro, normal_style))
    
    tc_points = [
        "1. This document is system-generated and does not require a physical signature. The digital trails and logs within the eBharat Portal serve as binding proof of the transaction.",
        "2. The applicant/bidder is solely responsible for the authenticity and accuracy of the information provided during the submission process.",
        "3. The Government of India reserves the right to cancel, modify, or reject any application, bid, or funding allocation without assigning specific reasons, if found violating procurement norms.",
        "4. Any discrepancy found in the submitted documents or post-award verification will lead to immediate cancellation and possible blacklisting of the concerned company/individual.",
        "5. The details shown in this document reflect the database state at the time of generation. Any subsequent changes will not reflect retroactively and require a fresh generated document.",
        "6. In case of any dispute, the matter will be subjected to the jurisdiction of the central administration courts of India.",
        "7. For further details and complete portal usage policies, please refer strictly to the guidelines section available upon login."
    ]
    
    for point in tc_points:
        elements.append(Paragraph(point, normal_style))
        
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph("<i>End of Document</i>", ParagraphStyle('End', parent=normal_style, alignment=1, textColor=colors.grey)))


    # Build the PDF
    doc.build(elements, onFirstPage=draw_header, onLaterPages=draw_header)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    return pdf_bytes
