# Generated by Django 6.0.1 on 2026-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_time', models.CharField(blank=True, help_text='e.g., 10 AM – 2 PM IST', max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='Short detail below title', max_length=255, null=True)),
                ('event_type', models.CharField(choices=[('info', 'Information (Blue)'), ('warning', 'Warning (Amber)'), ('critical', 'Critical (Red)')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
