# Generated by Django 6.0.2 on 2026-04-04 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=50)),
                ('registered_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('gst_document', models.FileField(upload_to='tender_documents/gst/')),
                ('bidder_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('official_email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('financial_statement', models.FileField(upload_to='tender_documents/financial_statements/')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('technical_document', models.FileField(upload_to='tender_documents/technical/')),
                ('financial_document', models.FileField(upload_to='tender_documents/financial/')),
                ('other_document', models.FileField(blank=True, null=True, upload_to='tender_documents/other/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('awarded', '🏆 Awarded')], default='pending', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tenders.tenderss')),
            ],
        ),
    ]
