# Generated by Django 6.0.1 on 2026-04-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderapplication',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
