# Generated by Django 6.0.2 on 2026-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('creator', 'Tender Creator'), ('bidder', 'Bidder')], max_length=20, null=True),
        ),
    ]
