# Generated by Django 6.0.1 on 2026-04-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrequest',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='tender_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
